export const FriendsList = [{
    id: 1,
    gender: "M",
    url: 'https://rickandmortyapi.com/api/character/avatar/18.jpeg',
    name: 'Andrzej',
    age: 22,
    city: 'Olsztyn',
    favQuote: 'Pycha kroczy przed upadkiem',
      favSong: 'Mata - schodki',
      favBook: 'Cień wiatru'
  },
  {
    id: 2,
    gender: "M",
    url: 'https://rickandmortyapi.com/api/character/avatar/19.jpeg',
    name: 'Jacek',
    age: 25,
    city: 'Szczecin',
    favQuote: 'Pieniądze szczęścia nie dają',
    favSong: 'Sanah - Marcepan',
    favBook: 'Małe życie'
  },
  {
    id: 3,
    gender: "F",
    url: 'https://rickandmortyapi.com/api/character/avatar/9.jpeg',
    name: 'Agata',
    age: 23,
    city: 'Warszawa',
    favQuote: 'Cierpliwy kamień ugotuje',
    favSong: 'ReTo - Klej',
    favBook: 'Millennium - cała seria'
  },
  {
    id: 4,
    gender: "F",
    url: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
    name: 'Paulina',
    age: 18,
    city: 'Radom',
    favQuote: 'Książki są lustrem, widzisz w nich to, co już masz w sobie',
    favSong: 'Gibbs - znikam',
    favBook: 'Oddam Ci słońce'
  }, 
  {
    id: 5,
    gender: "F",
    url: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
    name: 'Olga',
    age: 19,
    city: 'Radom',
    favQuote: 'Samych siebie poznajemy wtedy, kiedy możemy się przejrzeć w oczach innych ludzi',
    favSong: 'Myslovitz - Scenariusz dla moich sąsiadów',
    favBook: 'Przebudzenie'
  },
  {
    id: 6,
    gender: "F",
    url: 'https://rickandmortyapi.com/api/character/avatar/12.jpeg',
    name: 'Janina',
    age: 27,
    city: 'Szczecin',
    favQuote: 'Książki są lustrem, widzisz w nich to, co już masz w sobie',
    favSong: 'Gibbs - znikam',
    favBook: 'Oddam Ci słońce'
  },
  {
    id: 7,
    gender: "F",
    url: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
    name: 'Paulina',
    age: 22,
    city: 'Olsztyn',
    favQuote: 'Cierpliwy kamień ugotuje',
    favSong: 'ReTo - Klej',
    favBook: 'Millennium - cała seria'
  },
  {
    id: 8,
    gender: "M",
    url: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
    name: 'Patryk',
    age: 18,
    city: 'Radom',
    favQuote: 'Pieniądze szczęścia nie dają',
    favSong: 'Sanah - Marcepan',
    favBook: 'Małe życie'
  },
  {
    id: 9,
    gender: "F",
    url: 'https://rickandmortyapi.com/api/character/avatar/16.jpeg',
    name: 'Patrycja',
    age: 31,
    city: 'Szczecin',
    favQuote: 'Książki są lustrem, widzisz w nich to, co już masz w sobie',
    favSong: 'Gibbs - znikam',
    favBook: 'Oddam Ci słońce'
  },
  {
    id: 10,
    gender: "F",
    url: 'https://rickandmortyapi.com/api/character/avatar/6.jpeg',
    name: 'Renata',
    age: 33,
    city: 'Olsztyn',
    favQuote: 'I am learning that life is okay',
    favSong: 'A-ha - Take on me',
    favBook: 'Romeo i Julia'
  },
  {
    id: 11,
    gender: "M",
    url: 'https://rickandmortyapi.com/api/character/avatar/21.jpeg',
    name: 'Piotr',
    age: 20,
    city: 'Szczecin',
    favQuote: 'Just because I am losing, does not mean I am lost',
    favSong: 'Artur Rojek - Syreny',
    favBook: 'Mały książę'
  },
  {
    id: 12,
    gender: "M",
    url: 'https://rickandmortyapi.com/api/character/avatar/14.jpeg',
    name: 'Tadeusz',
    age: 19,
    city: 'Olsztyn',
    favQuote: 'Cierpliwy kamień ugotuje',
    favSong: 'ReTo - Klej',
    favBook: 'Millennium - cała seria'
  },
  {
    id: 13,
    gender: "M",
    url: 'https://rickandmortyapi.com/api/character/avatar/11.jpeg',
    name: 'Karol',
    age: 26,
    city: 'Szczecin',
    favQuote: 'Just because I am losing, does not mean I am lost',
    favSong: 'Artur Rojek - Syreny',
    favBook: 'Mały książę'
  },
  {
    id: 14,
    gender: "M",
    url: 'https://rickandmortyapi.com/api/character/avatar/15.jpeg',
    name: 'Grzegorz',
    age: 21,
    city: 'Radom',
    favQuote: 'I am learning that life is okay',
    favSong: 'A-ha - Take on me',
    favBook: 'Romeo i Julia'
  },
  {
    id: 15,
    gender: "M",
    url: 'https://rickandmortyapi.com/api/character/avatar/13.jpeg',
    name: 'Krzysztof',
    age: 30,
    city: 'Warszawa',
    favQuote: 'Just because I am losing, does not mean I am lost',
    favSong: 'Artur Rojek - Syreny',
    favBook: 'Mały książę'
  },
  {
    id: 16,
    gender: "F",
    url: 'https://rickandmortyapi.com/api/character/avatar/1.jpeg',
    name: 'Agnieszka',
    age: 28,
    city: 'Warszawa',
    favQuote: 'Książki są lustrem, widzisz w nich to, co już masz w sobie',
    favSong: 'Gibbs - znikam',
    favBook: 'Oddam Ci słońce'
  },
  {
    id: 17,
    gender: "F",
    url: 'https://rickandmortyapi.com/api/character/avatar/2.jpeg',
    name: 'Paulina',
    age: 22,
    city: 'Szczecin',
    favQuote: 'Pieniądze szczęścia nie dają',
    favSong: 'Sanah - Marcepan',
    favBook: 'Małe życie'
  },
  {
    id: 18,
    gender: "F",
    url: 'https://rickandmortyapi.com/api/character/avatar/7.jpeg',
    name: 'Paulina',
    age: 23,
    city: 'Warszawa',
    favQuote: 'Samych siebie poznajemy wtedy, kiedy możemy się przejrzeć w oczach innych ludzi',
    favSong: 'Myslovitz - Scenariusz dla moich sąsiadów',
    favBook: 'Przebudzenie'
  },
  {
    id: 19,
    gender: "F",
    url: 'https://rickandmortyapi.com/api/character/avatar/11.jpeg',
    name: 'Sandra',
    age: 18,
    city: 'Radom',
    favQuote: 'Just because I am losing, does not mean I am lost',
    favSong: 'Artur Rojek - Syreny',
    favBook: 'Mały książę'
  },
  {
    id: 20,
    gender: "M",
    url: 'https://rickandmortyapi.com/api/character/avatar/3.jpeg',
    name: 'Janusz',
    age: 20,
    city: 'Warszawa',
    favQuote: 'Samych siebie poznajemy wtedy, kiedy możemy się przejrzeć w oczach innych ludzi',
    favSong: 'Myslovitz - Scenariusz dla moich sąsiadów',
    favBook: 'Przebudzenie'
  },
  {
    id: 21,
    gender: "M",
    url: 'https://rickandmortyapi.com/api/character/avatar/4.jpeg',
    name: 'Jan',
    age: 29,
    city: 'Warszawa',
    favQuote: 'Samych siebie poznajemy wtedy, kiedy możemy się przejrzeć w oczach innych ludzi',
    favSong: 'Myslovitz - Scenariusz dla moich sąsiadów',
    favBook: 'Przebudzenie'
  }
]
